baseURL = "https://yourusername.github.io/sdlf-workshop/"
languageCode = "en-us"
title = "Serverless Data Lake Framework Workshop"
theme = "learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one.
  themeVariant = "aws"
  # Show visited links
  showVisitedLinks = true
  # Hide Next/Prev buttons
  disableNextPrev = false
  # Display breadcrumbs
  disableBreadcrumb = false
  # Hide search box
  disableSearch = false
  # Order sections in menu by "weight" or "title"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one
  # Possible values: red, blue, green, gold, aws
  themeVariant = "aws"

# Multi-language setup
[Languages]
[Languages.en]
title = "Serverless Data Lake Framework Workshop"
weight = 1
languageName = "English"

[Languages.vi]
title = "Workshop Serverless Data Lake Framework"
weight = 2
languageName = "Tiếng Việt"